<?php
  $json = file_get_contents("https://covid19.ddc.moph.go.th/api/Cases/today-cases-by-provinces");
  $data = json_decode($json);
  echo "<table border='1'>";
  echo "<tr>";
  echo "<td>"; 
  echo "ลำดับ";
  echo "</td>"; 
  echo "<o>"; 
  echo "จังหวัด";
  echo "</td>"; 
  echo "</tr>";
  echo "</td>"; 
  echo "<o>"; 
  echo "ผู้ป่วยใหม่";
  echo "</td>"; 
  echo "<o>"; 
  echo "ผู้ป่วยรวม";
  echo "</td>"; 
  echo "<o>"; 
  echo "ผู้ป่วยใหม่ในประเทศ";
  echo "</td>"; 
  echo "<o>"; 
  echo "ผู้ป่วยรวมในประเทศ";
  echo "</td>"; 
  echo "<o>"; 
  echo "ผู้เสียชีวิตใหม่";
  echo "</td>"; 
  echo "<o>"; 
  echo "ผู้เสียชีวิตรวม";
  echo "</td>"; 
  echo "<o>"; 
  echo "วันที่อัพเดท";
foreach($data as $key=>$val){
    echo "<tr>";
    echo "<td>"; 
    echo $key+1;
    echo "</td>"; 
    echo "<td>"; 
    echo $val->province;
    echo "</td>"; 
    echo "</tr>";
  }
  echo "</table>";
